#!/bin/bash
#
#  generate a UML diagram from PHP source model 
#
if [ $# -eq 2 ]; then
    echo input directory is $1
    echo ouput diagram file is $2.png
    /opt/phuml-master/src/app/phuml -r $1 -graphviz -createAssociations false -neato $2.png
    echo UML Diagram located at: file://$2.png
else 
    echo "No arguments provided"
    echo "proper form is phpuml <source dir> <uml drawing path/file>"
    exit 1
fi

