framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        #failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            # sync: 'sync://'

        routing:
            # Route your messages to the transports
            # 'App\Message\YourMessage': async

when@dev:
    framework:
        messenger:
            transports:
                in_memory: 'in-memory://'
            routing:
                'App\Message\DoiMessage': in_memory

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'

when@prod:
    framework:
    messenger:
        failure_transport: failed

        transports:
            async_normal:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: normal
            failed:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: failed
            async_low:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: low
            async_doi:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: doi

        routing:
            # Slow running Handlers
            'App\Message\ZipDatasetFiles': async_low

            # Normal Handlers
            'App\Message\DatasetSubmissionFiler': async_normal
            'App\Message\RenameFile': async_normal
            'App\Message\DeleteFile': async_normal
            'App\Message\DeleteDir': async_normal
            'App\Message\InformationProductFiler': async_normal

            # DOI Handler
            'App\Message\DoiMessage': async_doi
