# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle/tree/master/Resources/doc/index.md
oneup_flysystem:
    adapters:
        data_store_adapter:
            local:
                directory: '%env(DATA_STORE_DIRECTORY)%'
    filesystems:
        datastore_flysystem:
            adapter: data_store_adapter
            #alias: League\Flysystem\Filesystem
