services:
  database:
    image: postgis/postgis:14-3.5
    container_name: postgis
    restart: no
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    labels:
      com.symfony.server.service-ignore: true
  elasticsearch:
    image: elastic/elasticsearch:7.17.28
    container_name: elasticsearch
    restart: no
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ports:
      - 9200:9200
  application:
    image: rocky-pelagos:latest
    container_name: pelagos
    restart: no
    ports:
      - 8080:8080
    volumes:
      - ./docker_init_pelagos.sh:/usr/local/bin/docker_init_pelagos.sh
      - ./.env.local:/.env.local # yes, put at / for now.
      - ./newest-pelagos.sql:/opt/newest-pelagos.sql
    entrypoint: ["/usr/local/bin/docker_init_pelagos.sh"]  # Run the script as the entrypoint
