services:
  database:
    image: postgis/postgis:14-3.5
    container_name: postgis
    restart: no
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    labels:
      com.symfony.server.service-ignore: true
  elasticsearch:
    image: elastic/elasticsearch:7.17.28
    container_name: elasticsearch
    restart: no
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ports:
      - 9200:9200
  openldap:
    image: bitnami/openldap:latest
    container_name: openldap
    ports:
      - 389:389
    environment:
      - LDAP_PORT_NUMBER=389
      - LDAP_ROOT=dc=griidc,dc=org
      - LDAP_BASE=dc=griidc,dc=org
      - LDAP_BIND_DN=${LDAP_BIND_DN}
      - LDAP_BIND_PASSWORD=${LDAP_BIND_PW}
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PW}

