//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.29 at 04:06:17 PM CDT 
//


package edu.tamucc.hri.griidc.pubs.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.loc.gov/mods/v3}mods"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "mods"
})
@XmlRootElement(name = "recordData", namespace = "http://www.loc.gov/zing/srw/")
public class RecordData {

    @XmlElement(required = true)
    protected Mods mods;

    /**
     * Gets the value of the mods property.
     * 
     * @return
     *     possible object is
     *     {@link Mods }
     *     
     */
    public Mods getMods() {
        return mods;
    }

    /**
     * Sets the value of the mods property.
     * 
     * @param value
     *     allowed object is
     *     {@link Mods }
     *     
     */
    public void setMods(Mods value) {
        this.mods = value;
    }

}
