//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.29 at 04:06:17 PM CDT 
//


package edu.tamucc.hri.griidc.pubs.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.loc.gov/mods/v3}roleTerm"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "roleTerm"
})
@XmlRootElement(name = "role")
public class Role {

    @XmlElement(required = true)
    protected RoleTerm roleTerm;

    /**
     * Gets the value of the roleTerm property.
     * 
     * @return
     *     possible object is
     *     {@link RoleTerm }
     *     
     */
    public RoleTerm getRoleTerm() {
        return roleTerm;
    }

    /**
     * Sets the value of the roleTerm property.
     * 
     * @param value
     *     allowed object is
     *     {@link RoleTerm }
     *     
     */
    public void setRoleTerm(RoleTerm value) {
        this.roleTerm = value;
    }

}
