<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250815142105 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP SEQUENCE research_group_id_seq CASCADE');
        $this->addSql('ALTER TABLE data_center ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE data_repository ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE data_repository_role ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE dataset ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE dataset_link ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE dataset_publication ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE dataset_submission ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE dataset_submission_review ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE dif ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE digital_resource_type_descriptor ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE distribution_point ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE doi ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE file ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE fileset ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE funder ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE funding_cycle ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE funding_organization ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE funding_organization_role ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE information_product ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE keyword ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE log_action_item ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE login_attempts ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE password ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE person ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE person_data_repository ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE person_dataset_submission ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE person_funding_organization ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE person_research_group ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN person_token.valid_for IS \'\'');
        $this->addSql('ALTER TABLE product_type_descriptor ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE publication ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE research_group_role ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SEQUENCE research_group_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('ALTER TABLE data_center ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE data_repository ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE data_repository_role ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE dataset ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE dataset_link ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE dataset_publication ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE dataset_submission ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE dataset_submission_review ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE dif ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE digital_resource_type_descriptor ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE distribution_point ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE doi ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE file ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE fileset ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE funder ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE funding_cycle ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE funding_organization ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE funding_organization_role ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE information_product ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE keyword ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE log_action_item ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE login_attempts ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE password ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE person ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE person_data_repository ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE person_dataset_submission ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE person_funding_organization ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE person_research_group ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN person_token.valid_for IS \'(DC2Type:dateinterval)\'');
        $this->addSql('ALTER TABLE product_type_descriptor ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE publication ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE research_group_role ALTER id DROP IDENTITY');
    }
}
