#!/usr/bin/perl

use DBI;
use Config::Tiny;

my $config = Config::Tiny->read('ris2griidc.ini');

@cols_proj = ('ID','Title','FundSrc','LeadInstitution','SubTasks','StartDate','EndDate','ExtDate','Goals','Purpose','Objective','Abstract','Location','WebAddr','SGLink','SGRecID','Comment','Completed','Theme1','Theme2','Theme3','Theme4','Theme5');

@ris_cols_proj = map { "Program_$_"; } @cols_proj;

@griidc_cols_proj = map { "\"$_\""; } @cols_proj;

my $ris_dbh = DBI->connect('DBI:mysql:gomri_rpis',$config->{'ris'}->{'username'},$config->{'ris'}->{'password'}) or die "Couldn't connect to database: " . DBI->errstr;

my $ris_sth = $ris_dbh->prepare('SELECT ' . join(',',@ris_cols_proj) . ' FROM Programs WHERE Program_FundSrc > 0') or die "Couldn't prepare statement: " . $ris_dbh->errstr;

$ris_sth->execute() or die "Couldn't execute statement: " . $ris_sth->errstr;

my $griidc_dbh = DBI->connect('DBI:Pg:dbname=gomri',$config->{'griidc'}->{'username'},$config->{'griidc'}->{'password'}) or die "Couldn't connect to database: " . DBI->errstr;

$griidc_dbh->do("DELETE FROM projects;") or die "Couldn't execute statement: " . $griidc_dbh->errstr;

while (@row = $ris_sth->fetchrow_array()) {
    @row = map {
        s/\xA0/ /g; # replace nonbreaking space with regular space (0xA0 is an invalid UTF-8 character)
        if ($_ eq '' or $_ eq '0000-00-00' or $_ eq 'http://') { $_ = undef; } # make things null that should be
        /^\d{4}-\d\d-00$/ and $_ =~ s/00$/01/; # fix invalid dates
        $_;
    } @row;
    my $griidc_sth = $griidc_dbh->prepare('INSERT INTO projects (' . join(',',@griidc_cols_proj) . ') VALUES (' . join(',',('?') x @griidc_cols_proj) . ')');
    $griidc_sth->execute(@row);
}
