#!/bin/bash
#  jvh
# 
# run the   PubsToGriidcMain.class
#   set the class path to include postgresql jdbc connector,mysql connector, ini4j and javamail
#
export JAVA_APPLIB=/usr/share/java
CLASSPATH=$JAVA_APPLIB/ini4j.jar:$JAVA_APPLIB/javamail.jar:$JAVA_APPLIB/mysql-connector-java.jar:$JAVA_APPLIB/postgresql91-jdbc.jar 
CLASSPATH=$CLASSPATH:$HOME/griidcProjects/lib/RisToGriidc.jar
export CLASSPATH
echo java -cp $CLASSPATH edu.tamucc.hri.griidc.pubs.PubsToGriidcMain $1 $2 $3
java -cp $CLASSPATH edu.tamucc.hri.griidc.pubs.PubsToGriidcMain  $1 $2 $3
