# Configuration settings specific to the Drupal development environment.

imports:
    - { resource: config_drupal.yml }
    - { resource: parameters_drupal_dev.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_drupal_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

doctrine:
    orm:
        metadata_cache_driver: array
        query_cache_driver: array

monolog:
    handlers:
        filer:
            type:     stream
            path:     "%kernel.logs_dir%/filer.log"
            channels: ["filer"]
        retriever:
            type:     stream
            path:     "%kernel.logs_dir%/retriever.log"
            channels: ["retriever"]
        create_homedir:
            type:     stream
            path:     "%kernel.logs_dir%/create_homedir.log"
            channels: ["create_homedir"]
        dataset_file_hasher:
            type:     stream
            path:     "%kernel.logs_dir%/dataset_file_hasher.log"
            channels: ["dataset_file_hasher"]
        doi_issue:
            type:     stream
            path:     "%kernel.logs_dir%/doi_issue.log"
            channels: ["doi_issue"]
        login_attempts:
            type:     stream
            path:     "%kernel.logs_dir%/login_attempts.log"
            channels: ["login_attempts"]
        main:
            type:   stream
            path:   "%kernel.logs_dir%/%kernel.environment%.log"
            level:  debug
        console:
            type:   console
            bubble: false
            verbosity_levels:
                VERBOSITY_VERBOSE: INFO
                VERBOSITY_VERY_VERBOSE: DEBUG
            channels: ["!doctrine"]
        console_very_verbose:
            type:   console
            bubble: false
            verbosity_levels:
                VERBOSITY_VERBOSE: NOTICE
                VERBOSITY_VERY_VERBOSE: NOTICE
                VERBOSITY_DEBUG: DEBUG
            channels: ["doctrine"]
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type:   firephp
        #    level:  info
        #chromephp:
        #    type:   chromephp
        #    level:  info

#swiftmailer:
#    delivery_address: me@example.com
