# Configuration parameters common to all Drupal environments

imports:
    - { resource: config.yml }
    - { resource: security_drupal.yml }

framework:
    assets:
        base_path: ~


twig:
    globals:
        wrapped: true
