# Configuration settings specific to the Drupal production environment.

imports:
    - { resource: config_drupal.yml }
    - { resource: parameters_drupal_prod.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_drupal.yml"

fos_js_routing:
    request_context_base_url: /pelagos-symfony

monolog:
    handlers:
        filer:
            type:     stream
            path:     "%kernel.logs_dir%/filer.log"
            channels: ["filer"]
        retriever:
            type:     stream
            path:     "%kernel.logs_dir%/retriever.log"
            channels: ["retriever"]
        create_homedir:
            type:     stream
            path:     "%kernel.logs_dir%/create_homedir.log"
            channels: ["create_homedir"]
        dataset_file_hasher:
            type:     stream
            path:     "%kernel.logs_dir%/dataset_file_hasher.log"
            channels: ["dataset_file_hasher"]
        doi_issue:
            type:     stream
            path:     "%kernel.logs_dir%/doi_issue.log"
            channels: ["doi_issue"]
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type:  console
