check_google:
    path: /login/check-google

pelagos_legacy:
    resource: "@PelagosLegacyBundle/Resources/config/routing.yml"
    prefix:   /legacy

pelagos:
    resource: "@PelagosAppBundle/Resources/config/routing.yml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

redirecting:
    resource: "@PelagosAppBundle/Controller/RedirectingController.php"
    type: annotation
