<?php declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20191205223937 extends AbstractMigration
{
    public function up(Schema $schema) :void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'postgresql', 'Migration can only be executed safely on \'postgresql\'.');

        $this->addSql('DROP TABLE person_research_group_audit');
        $this->addSql('DROP TABLE data_center_audit');
        $this->addSql('DROP TABLE dataset_audit');
        $this->addSql('DROP TABLE dataset_submission_audit');
        $this->addSql('DROP TABLE dif_audit');
        $this->addSql('DROP TABLE data_repository_audit');
        $this->addSql('DROP TABLE distribution_point_audit');
        $this->addSql('DROP TABLE person_data_repository_audit');
        $this->addSql('DROP TABLE funding_cycle_audit');
        $this->addSql('DROP TABLE person_audit');
        $this->addSql('DROP TABLE funding_organization_audit');
        $this->addSql('DROP TABLE person_funding_organization_audit');
        $this->addSql('DROP TABLE research_group_audit');
        $this->addSql('ALTER TABLE person_token ALTER valid_for TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE person_token ALTER valid_for DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN person_token.valid_for IS \'(DC2Type:dateinterval)\'');
        $this->addSql('ALTER TABLE research_group ALTER locked DROP DEFAULT');
    }

    public function down(Schema $schema) :void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'postgresql', 'Migration can only be executed safely on \'postgresql\'.');

        $this->addSql('CREATE TABLE person_research_group_audit (id INT NOT NULL, rev INT NOT NULL, person_id INT DEFAULT NULL, research_group_id INT DEFAULT NULL, role_id INT DEFAULT NULL, creator_id INT DEFAULT NULL, modifier_id INT DEFAULT NULL, label TEXT DEFAULT NULL, creation_time_stamp TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, modification_time_stamp TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, revtype VARCHAR(4) NOT NULL, PRIMARY KEY(id, rev))');
        $this->addSql('CREATE INDEX rev_71e9a98e69179c5c224731ec9281c9d5_idx ON person_research_group_audit (rev)');
        $this->addSql('CREATE TABLE data_center_audit (id INT NOT NULL, rev INT NOT NULL, creator_id INT DEFAULT NULL, modifier_id INT DEFAULT NULL, organization_name citext DEFAULT NULL, organization_url TEXT DEFAULT NULL, phone_number TEXT DEFAULT NULL, delivery_point TEXT DEFAULT NULL, city TEXT DEFAULT NULL, administrative_area TEXT DEFAULT NULL, postal_code TEXT DEFAULT NULL, country TEXT DEFAULT NULL, email_address TEXT DEFAULT NULL, national_center BOOLEAN DEFAULT NULL, creation_time_stamp TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, modification_time_stamp TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, discr VARCHAR(255) DEFAULT NULL, revtype VARCHAR(4) NOT NULL, PRIMARY KEY(id, rev))');
        $this->addSql('CREATE INDEX rev_63f075da226b08465e0170cecd95794b_idx ON data_center_audit (rev)');
        $this->addSql('CREATE TABLE dataset_audit (id INT NOT NULL, rev INT NOT NULL, research_group_id INT DEFAULT NULL, dif_id INT DEFAULT NULL, dataset_submission_id INT DEFAULT NULL, creator_id INT DEFAULT NULL, modifier_id INT DEFAULT NULL, udi TEXT DEFAULT NULL, identified_status SMALLINT DEFAULT NULL, dataset_submission_status SMALLINT DEFAULT NULL, dataset_status TEXT DEFAULT NULL, availability_status SMALLINT DEFAULT NULL, issue_tracking_ticket TEXT DEFAULT NULL, creation_time_stamp TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, modification_time_stamp TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, revtype VARCHAR(4) NOT NULL, title TEXT DEFAULT NULL, abstract TEXT DEFAULT NULL, doi_id INT DEFAULT NULL, accepted_date TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, PRIMARY KEY(id, rev))');
        $this->addSql('CREATE INDEX rev_e624f22cebb69839b78c500501429a05_idx ON dataset_audit (rev)');
        $this->addSql('CREATE TABLE dataset_submission_audit (id INT NOT NULL, rev INT NOT NULL, dataset_id INT DEFAULT NULL, creator_id INT DEFAULT NULL, modifier_id INT DEFAULT NULL, sequence INT DEFAULT NULL, title TEXT DEFAULT NULL, abstract TEXT DEFAULT NULL, authors TEXT DEFAULT NULL, point_of_contact_name TEXT DEFAULT NULL, point_of_contact_email TEXT DEFAULT NULL, restrictions TEXT DEFAULT NULL, dataset_file_transfer_type TEXT DEFAULT NULL, dataset_file_uri TEXT DEFAULT NULL, dataset_file_transfer_status TEXT DEFAULT NULL, dataset_file_name TEXT DEFAULT NULL, dataset_file_size BIGINT DEFAULT NULL, dataset_file_sha256hash TEXT DEFAULT NULL, metadata_file_transfer_type TEXT DEFAULT NULL, metadata_file_uri TEXT DEFAULT NULL, metadata_file_transfer_status TEXT DEFAULT NULL, metadata_file_name TEXT DEFAULT NULL, metadata_file_sha256hash TEXT DEFAULT NULL, dataset_status TEXT DEFAULT NULL, creation_time_stamp TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, modification_time_stamp TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, revtype VARCHAR(4) NOT NULL, status INT DEFAULT NULL, short_title TEXT DEFAULT NULL, reference_date TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, reference_date_type TEXT DEFAULT NULL, purpose TEXT DEFAULT NULL, supp_params TEXT DEFAULT NULL, supp_methods TEXT DEFAULT NULL, supp_instruments TEXT DEFAULT NULL, supp_samp_scales_rates TEXT DEFAULT NULL, supp_error_analysis TEXT DEFAULT NULL, supp_provenance TEXT DEFAULT NULL, theme_keywords JSON DEFAULT NULL, place_keywords JSON DEFAULT NULL, topic_keywords JSON DEFAULT NULL, spatial_extent TEXT DEFAULT NULL, spatial_extent_description TEXT DEFAULT NULL, temporal_extent_desc TEXT DEFAULT NULL, temporal_extent_begin_position TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, temporal_extent_end_position TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, distribution_format_name TEXT DEFAULT NULL, file_decompression_technique TEXT DEFAULT NULL, submission_time_stamp TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, submitter_id INT DEFAULT NULL, temporal_extent_nil_reason_type TEXT DEFAULT NULL, erddap_url TEXT DEFAULT NULL, dataset_submission_review_id INT DEFAULT NULL, dataset_file_url_last_checked_date TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, dataset_file_url_status_code TEXT DEFAULT NULL, dataset_file_cold_storage_archive_size BIGINT DEFAULT NULL, dataset_file_cold_storage_archive_sha256hash TEXT DEFAULT NULL, dataset_file_cold_storage_original_filename TEXT DEFAULT NULL, remotely_hosted_name TEXT DEFAULT NULL, remotely_hosted_description TEXT DEFAULT NULL, remotely_hosted_function TEXT DEFAULT NULL, PRIMARY KEY(id, rev))');
        $this->addSql('CREATE INDEX rev_430039370f5303f6a2ed2dc7c106d1b3_idx ON dataset_submission_audit (rev)');
        $this->addSql('COMMENT ON COLUMN dataset_submission_audit.theme_keywords IS \'(DC2Type:json_array)\'');
        $this->addSql('COMMENT ON COLUMN dataset_submission_audit.place_keywords IS \'(DC2Type:json_array)\'');
        $this->addSql('COMMENT ON COLUMN dataset_submission_audit.topic_keywords IS \'(DC2Type:json_array)\'');
        $this->addSql('CREATE TABLE dif_audit (id INT NOT NULL, rev INT NOT NULL, primary_point_of_contact_id INT DEFAULT NULL, secondary_point_of_contact_id INT DEFAULT NULL, creator_id INT DEFAULT NULL, modifier_id INT DEFAULT NULL, status SMALLINT DEFAULT NULL, title TEXT DEFAULT NULL, abstract TEXT DEFAULT NULL, field_of_study_ecological_biological BOOLEAN DEFAULT NULL, field_of_study_physical_oceanography BOOLEAN DEFAULT NULL, field_of_study_atmospheric BOOLEAN DEFAULT NULL, field_of_study_chemical BOOLEAN DEFAULT NULL, field_of_study_human_health BOOLEAN DEFAULT NULL, field_of_study_social_cultural_political BOOLEAN DEFAULT NULL, field_of_study_economics BOOLEAN DEFAULT NULL, field_of_study_other TEXT DEFAULT NULL, data_size TEXT DEFAULT NULL, variables_observed TEXT DEFAULT NULL, collection_method_field_sampling BOOLEAN DEFAULT NULL, collection_method_simulated_generated BOOLEAN DEFAULT NULL, collection_method_laboratory BOOLEAN DEFAULT NULL, collection_method_literature_based BOOLEAN DEFAULT NULL, collection_method_remote_sensing BOOLEAN DEFAULT NULL, collection_method_other TEXT DEFAULT NULL, estimated_start_date DATE DEFAULT NULL, estimated_end_date DATE DEFAULT NULL, spatial_extent_description TEXT DEFAULT NULL, spatial_extent_geometry TEXT DEFAULT NULL, national_data_archive_nodc BOOLEAN DEFAULT NULL, national_data_archive_storet BOOLEAN DEFAULT NULL, national_data_archive_gbif BOOLEAN DEFAULT NULL, national_data_archive_ncbi BOOLEAN DEFAULT NULL, national_data_archive_data_gov BOOLEAN DEFAULT NULL, national_data_archive_other TEXT DEFAULT NULL, ethical_issues TEXT DEFAULT NULL, ethical_issues_explanation TEXT DEFAULT NULL, remarks TEXT DEFAULT NULL, creation_time_stamp TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, modification_time_stamp TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, revtype VARCHAR(4) NOT NULL, approved_date TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, PRIMARY KEY(id, rev))');
        $this->addSql('CREATE INDEX rev_113fa8fdb01329a769aae235040fe67e_idx ON dif_audit (rev)');
        $this->addSql('CREATE TABLE data_repository_audit (id INT NOT NULL, rev INT NOT NULL, creator_id INT DEFAULT NULL, modifier_id INT DEFAULT NULL, name citext DEFAULT NULL, email_address citext DEFAULT NULL, description TEXT DEFAULT NULL, url TEXT DEFAULT NULL, phone_number TEXT DEFAULT NULL, delivery_point TEXT DEFAULT NULL, city TEXT DEFAULT NULL, administrative_area TEXT DEFAULT NULL, postal_code TEXT DEFAULT NULL, country TEXT DEFAULT NULL, creation_time_stamp TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, modification_time_stamp TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, revtype VARCHAR(4) NOT NULL, PRIMARY KEY(id, rev))');
        $this->addSql('CREATE INDEX rev_a866b5f3a5f73521e77ecb9287ac0857_idx ON data_repository_audit (rev)');
        $this->addSql('CREATE TABLE distribution_point_audit (id INT NOT NULL, rev INT NOT NULL, dataset_submission_id INT DEFAULT NULL, data_center_id INT DEFAULT NULL, creator_id INT DEFAULT NULL, modifier_id INT DEFAULT NULL, distribution_url TEXT DEFAULT NULL, role_code TEXT DEFAULT NULL, creation_time_stamp TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, modification_time_stamp TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, revtype VARCHAR(4) NOT NULL, PRIMARY KEY(id, rev))');
        $this->addSql('CREATE INDEX rev_5981170d628af3062b88a372edd65a0b_idx ON distribution_point_audit (rev)');
        $this->addSql('CREATE TABLE person_data_repository_audit (id INT NOT NULL, rev INT NOT NULL, person_id INT DEFAULT NULL, data_repository_id INT DEFAULT NULL, role_id INT DEFAULT NULL, creator_id INT DEFAULT NULL, modifier_id INT DEFAULT NULL, label TEXT DEFAULT NULL, creation_time_stamp TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, modification_time_stamp TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, revtype VARCHAR(4) NOT NULL, PRIMARY KEY(id, rev))');
        $this->addSql('CREATE INDEX rev_07dc736682092abc2e3fa598ec112518_idx ON person_data_repository_audit (rev)');
        $this->addSql('CREATE TABLE funding_cycle_audit (id INT NOT NULL, rev INT NOT NULL, funding_organization_id INT DEFAULT NULL, creator_id INT DEFAULT NULL, modifier_id INT DEFAULT NULL, name citext DEFAULT NULL, description TEXT DEFAULT NULL, url TEXT DEFAULT NULL, start_date DATE DEFAULT NULL, end_date DATE DEFAULT NULL, udi_prefix TEXT DEFAULT NULL, creation_time_stamp TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, modification_time_stamp TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, revtype VARCHAR(4) NOT NULL, sort_order INT DEFAULT NULL, PRIMARY KEY(id, rev))');
        $this->addSql('CREATE INDEX rev_a98ba133de3b2a8dbcb7a8346e81547f_idx ON funding_cycle_audit (rev)');
        $this->addSql('CREATE TABLE person_audit (id INT NOT NULL, rev INT NOT NULL, creator_id INT DEFAULT NULL, modifier_id INT DEFAULT NULL, first_name TEXT DEFAULT NULL, last_name citext DEFAULT NULL, email_address citext DEFAULT NULL, phone_number TEXT DEFAULT NULL, delivery_point TEXT DEFAULT NULL, city TEXT DEFAULT NULL, administrative_area TEXT DEFAULT NULL, postal_code TEXT DEFAULT NULL, country TEXT DEFAULT NULL, url TEXT DEFAULT NULL, organization TEXT DEFAULT NULL, "position" TEXT DEFAULT NULL, creation_time_stamp TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, modification_time_stamp TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, revtype VARCHAR(4) NOT NULL, PRIMARY KEY(id, rev))');
        $this->addSql('CREATE INDEX rev_907be00c9c366335b3359c1e8e2f6227_idx ON person_audit (rev)');
        $this->addSql('CREATE TABLE funding_organization_audit (id INT NOT NULL, rev INT NOT NULL, data_repository_id INT DEFAULT NULL, creator_id INT DEFAULT NULL, modifier_id INT DEFAULT NULL, name citext DEFAULT NULL, logo BYTEA DEFAULT NULL, email_address TEXT DEFAULT NULL, description TEXT DEFAULT NULL, url TEXT DEFAULT NULL, phone_number TEXT DEFAULT NULL, delivery_point TEXT DEFAULT NULL, city TEXT DEFAULT NULL, administrative_area TEXT DEFAULT NULL, postal_code TEXT DEFAULT NULL, country TEXT DEFAULT NULL, creation_time_stamp TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, modification_time_stamp TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, revtype VARCHAR(4) NOT NULL, sort_order INT DEFAULT NULL, short_name citext DEFAULT NULL, PRIMARY KEY(id, rev))');
        $this->addSql('CREATE INDEX rev_5eb2f7bb85a4fbc0eaf3364e10d48a9c_idx ON funding_organization_audit (rev)');
        $this->addSql('CREATE TABLE person_funding_organization_audit (id INT NOT NULL, rev INT NOT NULL, person_id INT DEFAULT NULL, funding_organization_id INT DEFAULT NULL, role_id INT DEFAULT NULL, creator_id INT DEFAULT NULL, modifier_id INT DEFAULT NULL, label TEXT DEFAULT NULL, creation_time_stamp TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, modification_time_stamp TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, revtype VARCHAR(4) NOT NULL, PRIMARY KEY(id, rev))');
        $this->addSql('CREATE INDEX rev_7d9955a069e3cb60e7c9a5c5686509bb_idx ON person_funding_organization_audit (rev)');
        $this->addSql('CREATE TABLE research_group_audit (id INT NOT NULL, rev INT NOT NULL, funding_cycle_id INT DEFAULT NULL, creator_id INT DEFAULT NULL, modifier_id INT DEFAULT NULL, name citext DEFAULT NULL, url TEXT DEFAULT NULL, phone_number TEXT DEFAULT NULL, delivery_point TEXT DEFAULT NULL, city TEXT DEFAULT NULL, administrative_area TEXT DEFAULT NULL, postal_code TEXT DEFAULT NULL, country TEXT DEFAULT NULL, description TEXT DEFAULT NULL, logo BYTEA DEFAULT NULL, email_address citext DEFAULT NULL, creation_time_stamp TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, modification_time_stamp TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, revtype VARCHAR(4) NOT NULL, short_name citext DEFAULT NULL, locked BOOLEAN DEFAULT NULL, PRIMARY KEY(id, rev))');
        $this->addSql('CREATE INDEX rev_f167a141eabdd0230c7408c3d0b8cea4_idx ON research_group_audit (rev)');
        $this->addSql('ALTER TABLE person_token ALTER valid_for TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE person_token ALTER valid_for DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN person_token.valid_for IS NULL');
        $this->addSql('ALTER TABLE research_group ALTER locked SET DEFAULT \'false\'');
    }
}
