<?php

namespace Pelagos\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Baseline Migration.
 */
class Version20160926171558 extends AbstractMigration
{
    /**
     * Bring an empty database up to this baseline version.
     *
     * @param Schema $schema The DBAL schema.
     *
     * @return void
     */
    public function up(Schema $schema)
    {
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'postgresql', 'Migration can only be executed safely on \'postgresql\'.');

        $this->addSql('CREATE SEQUENCE dataset_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE dataset_submission_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE doi_request_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE person_data_repository_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE publication_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE person_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE password_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE dif_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE funding_organization_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE data_repository_role_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE funding_organization_role_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE data_repository_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE research_group_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE metadata_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE research_group_role_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE person_funding_organization_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE person_research_group_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE dataset_publication_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE publication_citation_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE funding_cycle_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE dataset (id INT NOT NULL, research_group_id INT DEFAULT NULL, dif_id INT DEFAULT NULL, dataset_submission_id INT DEFAULT NULL, creator_id INT DEFAULT NULL, modifier_id INT DEFAULT NULL, udi TEXT DEFAULT NULL, title TEXT DEFAULT NULL, abstract TEXT DEFAULT NULL, doi TEXT DEFAULT NULL, identified_status SMALLINT NOT NULL, dataset_submission_status SMALLINT NOT NULL, metadata_status TEXT NOT NULL, availability_status SMALLINT NOT NULL, issue_tracking_ticket TEXT DEFAULT NULL, creation_time_stamp TIMESTAMP(0) WITH TIME ZONE NOT NULL, modification_time_stamp TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_B7A041D03AF8E8D ON dataset (research_group_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B7A041D031C84D2E ON dataset (dif_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B7A041D08488BA54 ON dataset (dataset_submission_id)');
        $this->addSql('CREATE INDEX IDX_B7A041D061220EA6 ON dataset (creator_id)');
        $this->addSql('CREATE INDEX IDX_B7A041D0D079F553 ON dataset (modifier_id)');
        $this->addSql('CREATE TABLE dataset_audit (id INT NOT NULL, rev INT NOT NULL, research_group_id INT DEFAULT NULL, dif_id INT DEFAULT NULL, dataset_submission_id INT DEFAULT NULL, creator_id INT DEFAULT NULL, modifier_id INT DEFAULT NULL, udi TEXT DEFAULT NULL, title TEXT DEFAULT NULL, abstract TEXT DEFAULT NULL, doi TEXT DEFAULT NULL, identified_status SMALLINT DEFAULT NULL, dataset_submission_status SMALLINT DEFAULT NULL, metadata_status TEXT DEFAULT NULL, availability_status SMALLINT DEFAULT NULL, issue_tracking_ticket TEXT DEFAULT NULL, creation_time_stamp TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, modification_time_stamp TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, revtype VARCHAR(4) NOT NULL, PRIMARY KEY(id, rev))');
        $this->addSql('CREATE TABLE dataset_submission (id INT NOT NULL, dataset_id INT DEFAULT NULL, creator_id INT DEFAULT NULL, modifier_id INT DEFAULT NULL, sequence INT NOT NULL, title TEXT NOT NULL, abstract TEXT NOT NULL, authors TEXT NOT NULL, point_of_contact_name TEXT NOT NULL, point_of_contact_email TEXT NOT NULL, restrictions TEXT NOT NULL, doi TEXT DEFAULT NULL, dataset_file_transfer_type TEXT DEFAULT NULL, dataset_file_uri TEXT DEFAULT NULL, dataset_file_transfer_status TEXT DEFAULT NULL, dataset_file_name TEXT DEFAULT NULL, dataset_file_size BIGINT DEFAULT NULL, dataset_file_md5hash TEXT DEFAULT NULL, dataset_file_sha1hash TEXT DEFAULT NULL, dataset_file_sha256hash TEXT DEFAULT NULL, dataset_file_availability_date DATE DEFAULT NULL, dataset_file_pull_certain_times_only BOOLEAN DEFAULT NULL, dataset_file_pull_start_time TIME(0) WITHOUT TIME ZONE DEFAULT NULL, dataset_file_pull_days TEXT DEFAULT NULL, dataset_file_pull_source_data BOOLEAN DEFAULT NULL, metadata_file_transfer_type TEXT DEFAULT NULL, metadata_file_uri TEXT DEFAULT NULL, metadata_file_transfer_status TEXT DEFAULT NULL, metadata_file_name TEXT DEFAULT NULL, metadata_file_sha256hash TEXT DEFAULT NULL, metadata_status TEXT NOT NULL, creation_time_stamp TIMESTAMP(0) WITH TIME ZONE NOT NULL, modification_time_stamp TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_FEFE73FCD47C2D1B ON dataset_submission (dataset_id)');
        $this->addSql('CREATE INDEX IDX_FEFE73FC61220EA6 ON dataset_submission (creator_id)');
        $this->addSql('CREATE INDEX IDX_FEFE73FCD079F553 ON dataset_submission (modifier_id)');
        $this->addSql('COMMENT ON COLUMN dataset_submission.dataset_file_pull_days IS \'(DC2Type:simple_array)\'');
        $this->addSql('CREATE TABLE dataset_submission_audit (id INT NOT NULL, rev INT NOT NULL, dataset_id INT DEFAULT NULL, creator_id INT DEFAULT NULL, modifier_id INT DEFAULT NULL, sequence INT DEFAULT NULL, title TEXT DEFAULT NULL, abstract TEXT DEFAULT NULL, authors TEXT DEFAULT NULL, point_of_contact_name TEXT DEFAULT NULL, point_of_contact_email TEXT DEFAULT NULL, restrictions TEXT DEFAULT NULL, doi TEXT DEFAULT NULL, dataset_file_transfer_type TEXT DEFAULT NULL, dataset_file_uri TEXT DEFAULT NULL, dataset_file_transfer_status TEXT DEFAULT NULL, dataset_file_name TEXT DEFAULT NULL, dataset_file_size BIGINT DEFAULT NULL, dataset_file_md5hash TEXT DEFAULT NULL, dataset_file_sha1hash TEXT DEFAULT NULL, dataset_file_sha256hash TEXT DEFAULT NULL, dataset_file_availability_date DATE DEFAULT NULL, dataset_file_pull_certain_times_only BOOLEAN DEFAULT NULL, dataset_file_pull_start_time TIME(0) WITHOUT TIME ZONE DEFAULT NULL, dataset_file_pull_days TEXT DEFAULT NULL, dataset_file_pull_source_data BOOLEAN DEFAULT NULL, metadata_file_transfer_type TEXT DEFAULT NULL, metadata_file_uri TEXT DEFAULT NULL, metadata_file_transfer_status TEXT DEFAULT NULL, metadata_file_name TEXT DEFAULT NULL, metadata_file_sha256hash TEXT DEFAULT NULL, metadata_status TEXT DEFAULT NULL, creation_time_stamp TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, modification_time_stamp TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, revtype VARCHAR(4) NOT NULL, PRIMARY KEY(id, rev))');
        $this->addSql('COMMENT ON COLUMN dataset_submission_audit.dataset_file_pull_days IS \'(DC2Type:simple_array)\'');
        $this->addSql('CREATE TABLE doi_request (id INT NOT NULL, creator_id INT DEFAULT NULL, modifier_id INT DEFAULT NULL, doi TEXT DEFAULT NULL, status SMALLINT NOT NULL, url TEXT NOT NULL, responsible_party TEXT NOT NULL, title TEXT NOT NULL, publisher TEXT NOT NULL, publication_date DATE NOT NULL, creation_time_stamp TIMESTAMP(0) WITH TIME ZONE NOT NULL, modification_time_stamp TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_715B8DDF61220EA6 ON doi_request (creator_id)');
        $this->addSql('CREATE INDEX IDX_715B8DDFD079F553 ON doi_request (modifier_id)');
        $this->addSql('CREATE TABLE person_data_repository (id INT NOT NULL, person_id INT DEFAULT NULL, data_repository_id INT DEFAULT NULL, role_id INT DEFAULT NULL, creator_id INT DEFAULT NULL, modifier_id INT DEFAULT NULL, label TEXT NOT NULL, creation_time_stamp TIMESTAMP(0) WITH TIME ZONE NOT NULL, modification_time_stamp TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_524FAD8F217BBB47 ON person_data_repository (person_id)');
        $this->addSql('CREATE INDEX IDX_524FAD8FA18BC0DD ON person_data_repository (data_repository_id)');
        $this->addSql('CREATE INDEX IDX_524FAD8FD60322AC ON person_data_repository (role_id)');
        $this->addSql('CREATE INDEX IDX_524FAD8F61220EA6 ON person_data_repository (creator_id)');
        $this->addSql('CREATE INDEX IDX_524FAD8FD079F553 ON person_data_repository (modifier_id)');
        $this->addSql('CREATE TABLE person_data_repository_audit (id INT NOT NULL, rev INT NOT NULL, person_id INT DEFAULT NULL, data_repository_id INT DEFAULT NULL, role_id INT DEFAULT NULL, creator_id INT DEFAULT NULL, modifier_id INT DEFAULT NULL, label TEXT DEFAULT NULL, creation_time_stamp TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, modification_time_stamp TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, revtype VARCHAR(4) NOT NULL, PRIMARY KEY(id, rev))');
        $this->addSql('CREATE TABLE publication (id INT NOT NULL, creator_id INT DEFAULT NULL, modifier_id INT DEFAULT NULL, doi citext NOT NULL, creation_time_stamp TIMESTAMP(0) WITH TIME ZONE NOT NULL, modification_time_stamp TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_AF3C677961220EA6 ON publication (creator_id)');
        $this->addSql('CREATE INDEX IDX_AF3C6779D079F553 ON publication (modifier_id)');
        $this->addSql('CREATE TABLE person (id INT NOT NULL, creator_id INT DEFAULT NULL, modifier_id INT DEFAULT NULL, first_name TEXT NOT NULL, last_name citext NOT NULL, email_address citext NOT NULL, phone_number TEXT DEFAULT NULL, delivery_point TEXT DEFAULT NULL, city TEXT DEFAULT NULL, administrative_area TEXT DEFAULT NULL, postal_code TEXT DEFAULT NULL, country TEXT DEFAULT NULL, url TEXT DEFAULT NULL, organization TEXT DEFAULT NULL, position TEXT DEFAULT NULL, creation_time_stamp TIMESTAMP(0) WITH TIME ZONE NOT NULL, modification_time_stamp TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_34DCD176B08E074E ON person (email_address)');
        $this->addSql('CREATE INDEX IDX_34DCD17661220EA6 ON person (creator_id)');
        $this->addSql('CREATE INDEX IDX_34DCD176D079F553 ON person (modifier_id)');
        $this->addSql('CREATE TABLE person_audit (id INT NOT NULL, rev INT NOT NULL, creator_id INT DEFAULT NULL, modifier_id INT DEFAULT NULL, first_name TEXT DEFAULT NULL, last_name citext DEFAULT NULL, email_address citext DEFAULT NULL, phone_number TEXT DEFAULT NULL, delivery_point TEXT DEFAULT NULL, city TEXT DEFAULT NULL, administrative_area TEXT DEFAULT NULL, postal_code TEXT DEFAULT NULL, country TEXT DEFAULT NULL, url TEXT DEFAULT NULL, organization TEXT DEFAULT NULL, position TEXT DEFAULT NULL, creation_time_stamp TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, modification_time_stamp TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, revtype VARCHAR(4) NOT NULL, PRIMARY KEY(id, rev))');
        $this->addSql('CREATE TABLE account (person_id INT NOT NULL, password_id INT DEFAULT NULL, creator_id INT DEFAULT NULL, modifier_id INT DEFAULT NULL, user_id TEXT NOT NULL, posix BOOLEAN NOT NULL, uid_number INT DEFAULT NULL, gid_number INT DEFAULT NULL, home_directory TEXT DEFAULT NULL, login_shell TEXT DEFAULT NULL, ssh_public_keys TEXT DEFAULT NULL, creation_time_stamp TIMESTAMP(0) WITH TIME ZONE NOT NULL, modification_time_stamp TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY(person_id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7D3656A4A76ED395 ON account (user_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7D3656A4A54498BD ON account (uid_number)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7D3656A43E4A79C1 ON account (password_id)');
        $this->addSql('CREATE INDEX IDX_7D3656A461220EA6 ON account (creator_id)');
        $this->addSql('CREATE INDEX IDX_7D3656A4D079F553 ON account (modifier_id)');
        $this->addSql('COMMENT ON COLUMN account.ssh_public_keys IS \'(DC2Type:json_array)\'');
        $this->addSql('CREATE TABLE password (id INT NOT NULL, account_id INT DEFAULT NULL, creator_id INT DEFAULT NULL, modifier_id INT DEFAULT NULL, password_hash BYTEA NOT NULL, password_hash_algorithm TEXT NOT NULL, password_hash_salt BYTEA NOT NULL, creation_time_stamp TIMESTAMP(0) WITH TIME ZONE NOT NULL, modification_time_stamp TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_35C246D59B6B5FBA ON password (account_id)');
        $this->addSql('CREATE INDEX IDX_35C246D561220EA6 ON password (creator_id)');
        $this->addSql('CREATE INDEX IDX_35C246D5D079F553 ON password (modifier_id)');
        $this->addSql('CREATE TABLE dif (id INT NOT NULL, primary_point_of_contact_id INT DEFAULT NULL, secondary_point_of_contact_id INT DEFAULT NULL, creator_id INT DEFAULT NULL, modifier_id INT DEFAULT NULL, status SMALLINT NOT NULL, title TEXT NOT NULL, abstract TEXT NOT NULL, field_of_study_ecological_biological BOOLEAN DEFAULT NULL, field_of_study_physical_oceanography BOOLEAN DEFAULT NULL, field_of_study_atmospheric BOOLEAN DEFAULT NULL, field_of_study_chemical BOOLEAN DEFAULT NULL, field_of_study_human_health BOOLEAN DEFAULT NULL, field_of_study_social_cultural_political BOOLEAN DEFAULT NULL, field_of_study_economics BOOLEAN DEFAULT NULL, field_of_study_other TEXT DEFAULT NULL, data_size TEXT DEFAULT NULL, variables_observed TEXT DEFAULT NULL, collection_method_field_sampling BOOLEAN DEFAULT NULL, collection_method_simulated_generated BOOLEAN DEFAULT NULL, collection_method_laboratory BOOLEAN DEFAULT NULL, collection_method_literature_based BOOLEAN DEFAULT NULL, collection_method_remote_sensing BOOLEAN DEFAULT NULL, collection_method_other TEXT DEFAULT NULL, estimated_start_date DATE DEFAULT NULL, estimated_end_date DATE DEFAULT NULL, spatial_extent_description TEXT DEFAULT NULL, spatial_extent_geometry TEXT DEFAULT NULL, national_data_archive_nodc BOOLEAN DEFAULT NULL, national_data_archive_storet BOOLEAN DEFAULT NULL, national_data_archive_gbif BOOLEAN DEFAULT NULL, national_data_archive_ncbi BOOLEAN DEFAULT NULL, national_data_archive_data_gov BOOLEAN DEFAULT NULL, national_data_archive_other TEXT DEFAULT NULL, ethical_issues TEXT DEFAULT NULL, ethical_issues_explanation TEXT DEFAULT NULL, remarks TEXT DEFAULT NULL, creation_time_stamp TIMESTAMP(0) WITH TIME ZONE NOT NULL, modification_time_stamp TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_A071AE6D324E97C7 ON dif (primary_point_of_contact_id)');
        $this->addSql('CREATE INDEX IDX_A071AE6DBE394C04 ON dif (secondary_point_of_contact_id)');
        $this->addSql('CREATE INDEX IDX_A071AE6D61220EA6 ON dif (creator_id)');
        $this->addSql('CREATE INDEX IDX_A071AE6DD079F553 ON dif (modifier_id)');
        $this->addSql('CREATE TABLE dif_audit (id INT NOT NULL, rev INT NOT NULL, primary_point_of_contact_id INT DEFAULT NULL, secondary_point_of_contact_id INT DEFAULT NULL, creator_id INT DEFAULT NULL, modifier_id INT DEFAULT NULL, status SMALLINT DEFAULT NULL, title TEXT DEFAULT NULL, abstract TEXT DEFAULT NULL, field_of_study_ecological_biological BOOLEAN DEFAULT NULL, field_of_study_physical_oceanography BOOLEAN DEFAULT NULL, field_of_study_atmospheric BOOLEAN DEFAULT NULL, field_of_study_chemical BOOLEAN DEFAULT NULL, field_of_study_human_health BOOLEAN DEFAULT NULL, field_of_study_social_cultural_political BOOLEAN DEFAULT NULL, field_of_study_economics BOOLEAN DEFAULT NULL, field_of_study_other TEXT DEFAULT NULL, data_size TEXT DEFAULT NULL, variables_observed TEXT DEFAULT NULL, collection_method_field_sampling BOOLEAN DEFAULT NULL, collection_method_simulated_generated BOOLEAN DEFAULT NULL, collection_method_laboratory BOOLEAN DEFAULT NULL, collection_method_literature_based BOOLEAN DEFAULT NULL, collection_method_remote_sensing BOOLEAN DEFAULT NULL, collection_method_other TEXT DEFAULT NULL, estimated_start_date DATE DEFAULT NULL, estimated_end_date DATE DEFAULT NULL, spatial_extent_description TEXT DEFAULT NULL, spatial_extent_geometry TEXT DEFAULT NULL, national_data_archive_nodc BOOLEAN DEFAULT NULL, national_data_archive_storet BOOLEAN DEFAULT NULL, national_data_archive_gbif BOOLEAN DEFAULT NULL, national_data_archive_ncbi BOOLEAN DEFAULT NULL, national_data_archive_data_gov BOOLEAN DEFAULT NULL, national_data_archive_other TEXT DEFAULT NULL, ethical_issues TEXT DEFAULT NULL, ethical_issues_explanation TEXT DEFAULT NULL, remarks TEXT DEFAULT NULL, creation_time_stamp TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, modification_time_stamp TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, revtype VARCHAR(4) NOT NULL, PRIMARY KEY(id, rev))');
        $this->addSql('CREATE TABLE funding_organization (id INT NOT NULL, data_repository_id INT DEFAULT NULL, creator_id INT DEFAULT NULL, modifier_id INT DEFAULT NULL, name citext NOT NULL, logo BYTEA DEFAULT NULL, email_address TEXT DEFAULT NULL, description TEXT DEFAULT NULL, url TEXT DEFAULT NULL, phone_number TEXT DEFAULT NULL, delivery_point TEXT DEFAULT NULL, city TEXT DEFAULT NULL, administrative_area TEXT DEFAULT NULL, postal_code TEXT DEFAULT NULL, country TEXT DEFAULT NULL, sort_order INT DEFAULT NULL, creation_time_stamp TIMESTAMP(0) WITH TIME ZONE NOT NULL, modification_time_stamp TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2A1BCCA05E237E06 ON funding_organization (name)');
        $this->addSql('CREATE INDEX IDX_2A1BCCA0A18BC0DD ON funding_organization (data_repository_id)');
        $this->addSql('CREATE INDEX IDX_2A1BCCA061220EA6 ON funding_organization (creator_id)');
        $this->addSql('CREATE INDEX IDX_2A1BCCA0D079F553 ON funding_organization (modifier_id)');
        $this->addSql('CREATE TABLE funding_organization_audit (id INT NOT NULL, rev INT NOT NULL, data_repository_id INT DEFAULT NULL, creator_id INT DEFAULT NULL, modifier_id INT DEFAULT NULL, name citext DEFAULT NULL, logo BYTEA DEFAULT NULL, email_address TEXT DEFAULT NULL, description TEXT DEFAULT NULL, url TEXT DEFAULT NULL, phone_number TEXT DEFAULT NULL, delivery_point TEXT DEFAULT NULL, city TEXT DEFAULT NULL, administrative_area TEXT DEFAULT NULL, postal_code TEXT DEFAULT NULL, country TEXT DEFAULT NULL, sort_order INT DEFAULT NULL, creation_time_stamp TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, modification_time_stamp TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, revtype VARCHAR(4) NOT NULL, PRIMARY KEY(id, rev))');
        $this->addSql('CREATE TABLE data_repository_role (id INT NOT NULL, creator_id INT DEFAULT NULL, modifier_id INT DEFAULT NULL, name citext NOT NULL, weight INT NOT NULL, creation_time_stamp TIMESTAMP(0) WITH TIME ZONE NOT NULL, modification_time_stamp TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_91F6449561220EA6 ON data_repository_role (creator_id)');
        $this->addSql('CREATE INDEX IDX_91F64495D079F553 ON data_repository_role (modifier_id)');
        $this->addSql('CREATE TABLE funding_organization_role (id INT NOT NULL, creator_id INT DEFAULT NULL, modifier_id INT DEFAULT NULL, name citext NOT NULL, weight INT NOT NULL, creation_time_stamp TIMESTAMP(0) WITH TIME ZONE NOT NULL, modification_time_stamp TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_39E8B4E061220EA6 ON funding_organization_role (creator_id)');
        $this->addSql('CREATE INDEX IDX_39E8B4E0D079F553 ON funding_organization_role (modifier_id)');
        $this->addSql('CREATE TABLE data_repository (id INT NOT NULL, creator_id INT DEFAULT NULL, modifier_id INT DEFAULT NULL, name citext NOT NULL, email_address citext NOT NULL, description TEXT NOT NULL, url TEXT NOT NULL, phone_number TEXT NOT NULL, delivery_point TEXT NOT NULL, city TEXT NOT NULL, administrative_area TEXT NOT NULL, postal_code TEXT NOT NULL, country TEXT NOT NULL, creation_time_stamp TIMESTAMP(0) WITH TIME ZONE NOT NULL, modification_time_stamp TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_93CB6D145E237E06 ON data_repository (name)');
        $this->addSql('CREATE INDEX IDX_93CB6D1461220EA6 ON data_repository (creator_id)');
        $this->addSql('CREATE INDEX IDX_93CB6D14D079F553 ON data_repository (modifier_id)');
        $this->addSql('CREATE TABLE data_repository_audit (id INT NOT NULL, rev INT NOT NULL, creator_id INT DEFAULT NULL, modifier_id INT DEFAULT NULL, name citext DEFAULT NULL, email_address citext DEFAULT NULL, description TEXT DEFAULT NULL, url TEXT DEFAULT NULL, phone_number TEXT DEFAULT NULL, delivery_point TEXT DEFAULT NULL, city TEXT DEFAULT NULL, administrative_area TEXT DEFAULT NULL, postal_code TEXT DEFAULT NULL, country TEXT DEFAULT NULL, creation_time_stamp TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, modification_time_stamp TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, revtype VARCHAR(4) NOT NULL, PRIMARY KEY(id, rev))');
        $this->addSql('CREATE TABLE research_group (id INT NOT NULL, funding_cycle_id INT DEFAULT NULL, creator_id INT DEFAULT NULL, modifier_id INT DEFAULT NULL, name citext NOT NULL COLLATE "POSIX", url TEXT DEFAULT NULL, phone_number TEXT DEFAULT NULL, delivery_point TEXT DEFAULT NULL, city TEXT DEFAULT NULL, administrative_area TEXT DEFAULT NULL, postal_code TEXT DEFAULT NULL, country TEXT DEFAULT NULL, description TEXT DEFAULT NULL, logo BYTEA DEFAULT NULL, email_address citext DEFAULT NULL, creation_time_stamp TIMESTAMP(0) WITH TIME ZONE NOT NULL, modification_time_stamp TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_EB46262173FB1572 ON research_group (funding_cycle_id)');
        $this->addSql('CREATE INDEX IDX_EB46262161220EA6 ON research_group (creator_id)');
        $this->addSql('CREATE INDEX IDX_EB462621D079F553 ON research_group (modifier_id)');
        $this->addSql('CREATE TABLE research_group_audit (id INT NOT NULL, rev INT NOT NULL, funding_cycle_id INT DEFAULT NULL, creator_id INT DEFAULT NULL, modifier_id INT DEFAULT NULL, name citext DEFAULT NULL, url TEXT DEFAULT NULL, phone_number TEXT DEFAULT NULL, delivery_point TEXT DEFAULT NULL, city TEXT DEFAULT NULL, administrative_area TEXT DEFAULT NULL, postal_code TEXT DEFAULT NULL, country TEXT DEFAULT NULL, description TEXT DEFAULT NULL, logo BYTEA DEFAULT NULL, email_address citext DEFAULT NULL, creation_time_stamp TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, modification_time_stamp TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, revtype VARCHAR(4) NOT NULL, PRIMARY KEY(id, rev))');
        $this->addSql('CREATE TABLE metadata (id INT NOT NULL, dataset_id INT DEFAULT NULL, creator_id INT DEFAULT NULL, modifier_id INT DEFAULT NULL, xml XML NOT NULL, geometry geometry(GEOMETRY, 4326) DEFAULT NULL, extent_description TEXT DEFAULT NULL, title TEXT NOT NULL, abstract TEXT NOT NULL, begin_position TEXT DEFAULT NULL, end_position TEXT DEFAULT NULL, file_format TEXT DEFAULT NULL, purpose TEXT DEFAULT NULL, theme_keywords TEXT[] DEFAULT NULL, creation_time_stamp TIMESTAMP(0) WITH TIME ZONE NOT NULL, modification_time_stamp TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4F143414D47C2D1B ON metadata (dataset_id)');
        $this->addSql('CREATE INDEX IDX_4F14341461220EA6 ON metadata (creator_id)');
        $this->addSql('CREATE INDEX IDX_4F143414D079F553 ON metadata (modifier_id)');
        $this->addSql('COMMENT ON COLUMN metadata.xml IS \'(DC2Type:xml)\'');
        $this->addSql('COMMENT ON COLUMN metadata.geometry IS \'(DC2Type:geometry)\'');
        $this->addSql('COMMENT ON COLUMN metadata.theme_keywords IS \'(DC2Type:text_array)\'');
        $this->addSql('CREATE TABLE research_group_role (id INT NOT NULL, creator_id INT DEFAULT NULL, modifier_id INT DEFAULT NULL, name citext NOT NULL, weight INT NOT NULL, creation_time_stamp TIMESTAMP(0) WITH TIME ZONE NOT NULL, modification_time_stamp TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_BA29D77261220EA6 ON research_group_role (creator_id)');
        $this->addSql('CREATE INDEX IDX_BA29D772D079F553 ON research_group_role (modifier_id)');
        $this->addSql('CREATE TABLE person_funding_organization (id INT NOT NULL, person_id INT DEFAULT NULL, funding_organization_id INT DEFAULT NULL, role_id INT DEFAULT NULL, creator_id INT DEFAULT NULL, modifier_id INT DEFAULT NULL, label TEXT NOT NULL, creation_time_stamp TIMESTAMP(0) WITH TIME ZONE NOT NULL, modification_time_stamp TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_CE5D61F4217BBB47 ON person_funding_organization (person_id)');
        $this->addSql('CREATE INDEX IDX_CE5D61F45213C9D4 ON person_funding_organization (funding_organization_id)');
        $this->addSql('CREATE INDEX IDX_CE5D61F4D60322AC ON person_funding_organization (role_id)');
        $this->addSql('CREATE INDEX IDX_CE5D61F461220EA6 ON person_funding_organization (creator_id)');
        $this->addSql('CREATE INDEX IDX_CE5D61F4D079F553 ON person_funding_organization (modifier_id)');
        $this->addSql('CREATE TABLE person_funding_organization_audit (id INT NOT NULL, rev INT NOT NULL, person_id INT DEFAULT NULL, funding_organization_id INT DEFAULT NULL, role_id INT DEFAULT NULL, creator_id INT DEFAULT NULL, modifier_id INT DEFAULT NULL, label TEXT DEFAULT NULL, creation_time_stamp TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, modification_time_stamp TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, revtype VARCHAR(4) NOT NULL, PRIMARY KEY(id, rev))');
        $this->addSql('CREATE TABLE person_token (person_id INT NOT NULL, creator_id INT DEFAULT NULL, modifier_id INT DEFAULT NULL, valid_for INTERVAL NOT NULL, token_text TEXT NOT NULL, use TEXT NOT NULL, creation_time_stamp TIMESTAMP(0) WITH TIME ZONE NOT NULL, modification_time_stamp TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY(person_id))');
        $this->addSql('CREATE INDEX IDX_F301BEFF61220EA6 ON person_token (creator_id)');
        $this->addSql('CREATE INDEX IDX_F301BEFFD079F553 ON person_token (modifier_id)');
        $this->addSql('CREATE TABLE person_research_group (id INT NOT NULL, person_id INT DEFAULT NULL, research_group_id INT DEFAULT NULL, role_id INT DEFAULT NULL, creator_id INT DEFAULT NULL, modifier_id INT DEFAULT NULL, label TEXT NOT NULL, creation_time_stamp TIMESTAMP(0) WITH TIME ZONE NOT NULL, modification_time_stamp TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_E9B161F217BBB47 ON person_research_group (person_id)');
        $this->addSql('CREATE INDEX IDX_E9B161F3AF8E8D ON person_research_group (research_group_id)');
        $this->addSql('CREATE INDEX IDX_E9B161FD60322AC ON person_research_group (role_id)');
        $this->addSql('CREATE INDEX IDX_E9B161F61220EA6 ON person_research_group (creator_id)');
        $this->addSql('CREATE INDEX IDX_E9B161FD079F553 ON person_research_group (modifier_id)');
        $this->addSql('CREATE TABLE person_research_group_audit (id INT NOT NULL, rev INT NOT NULL, person_id INT DEFAULT NULL, research_group_id INT DEFAULT NULL, role_id INT DEFAULT NULL, creator_id INT DEFAULT NULL, modifier_id INT DEFAULT NULL, label TEXT DEFAULT NULL, creation_time_stamp TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, modification_time_stamp TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, revtype VARCHAR(4) NOT NULL, PRIMARY KEY(id, rev))');
        $this->addSql('CREATE TABLE dataset_publication (id INT NOT NULL, publication_id INT DEFAULT NULL, dataset_id INT DEFAULT NULL, creator_id INT DEFAULT NULL, modifier_id INT DEFAULT NULL, creation_time_stamp TIMESTAMP(0) WITH TIME ZONE NOT NULL, modification_time_stamp TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_3FA681C138B217A7 ON dataset_publication (publication_id)');
        $this->addSql('CREATE INDEX IDX_3FA681C1D47C2D1B ON dataset_publication (dataset_id)');
        $this->addSql('CREATE INDEX IDX_3FA681C161220EA6 ON dataset_publication (creator_id)');
        $this->addSql('CREATE INDEX IDX_3FA681C1D079F553 ON dataset_publication (modifier_id)');
        $this->addSql('CREATE TABLE publication_citation (id INT NOT NULL, publication_id INT DEFAULT NULL, creator_id INT DEFAULT NULL, modifier_id INT DEFAULT NULL, citation_text citext NOT NULL, style citext NOT NULL, locale citext NOT NULL, creation_time_stamp TIMESTAMP(0) WITH TIME ZONE NOT NULL, modification_time_stamp TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_D5DA692F38B217A7 ON publication_citation (publication_id)');
        $this->addSql('CREATE INDEX IDX_D5DA692F61220EA6 ON publication_citation (creator_id)');
        $this->addSql('CREATE INDEX IDX_D5DA692FD079F553 ON publication_citation (modifier_id)');
        $this->addSql('CREATE TABLE funding_cycle (id INT NOT NULL, funding_organization_id INT DEFAULT NULL, creator_id INT DEFAULT NULL, modifier_id INT DEFAULT NULL, name citext NOT NULL, description TEXT DEFAULT NULL, url TEXT DEFAULT NULL, start_date DATE DEFAULT NULL, end_date DATE DEFAULT NULL, udi_prefix TEXT DEFAULT NULL, sort_order INT DEFAULT NULL, creation_time_stamp TIMESTAMP(0) WITH TIME ZONE NOT NULL, modification_time_stamp TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_37E9C7605213C9D4 ON funding_cycle (funding_organization_id)');
        $this->addSql('CREATE INDEX IDX_37E9C76061220EA6 ON funding_cycle (creator_id)');
        $this->addSql('CREATE INDEX IDX_37E9C760D079F553 ON funding_cycle (modifier_id)');
        $this->addSql('CREATE TABLE funding_cycle_audit (id INT NOT NULL, rev INT NOT NULL, funding_organization_id INT DEFAULT NULL, creator_id INT DEFAULT NULL, modifier_id INT DEFAULT NULL, name citext DEFAULT NULL, description TEXT DEFAULT NULL, url TEXT DEFAULT NULL, start_date DATE DEFAULT NULL, end_date DATE DEFAULT NULL, udi_prefix TEXT DEFAULT NULL, sort_order INT DEFAULT NULL, creation_time_stamp TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, modification_time_stamp TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, revtype VARCHAR(4) NOT NULL, PRIMARY KEY(id, rev))');
        $this->addSql('CREATE TABLE revisions (id SERIAL NOT NULL, timestamp TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, username VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('ALTER TABLE dataset ADD CONSTRAINT FK_B7A041D03AF8E8D FOREIGN KEY (research_group_id) REFERENCES research_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE dataset ADD CONSTRAINT FK_B7A041D031C84D2E FOREIGN KEY (dif_id) REFERENCES dif (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE dataset ADD CONSTRAINT FK_B7A041D08488BA54 FOREIGN KEY (dataset_submission_id) REFERENCES dataset_submission (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE dataset ADD CONSTRAINT FK_B7A041D061220EA6 FOREIGN KEY (creator_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE dataset ADD CONSTRAINT FK_B7A041D0D079F553 FOREIGN KEY (modifier_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE dataset_submission ADD CONSTRAINT FK_FEFE73FCD47C2D1B FOREIGN KEY (dataset_id) REFERENCES dataset (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE dataset_submission ADD CONSTRAINT FK_FEFE73FC61220EA6 FOREIGN KEY (creator_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE dataset_submission ADD CONSTRAINT FK_FEFE73FCD079F553 FOREIGN KEY (modifier_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE doi_request ADD CONSTRAINT FK_715B8DDF61220EA6 FOREIGN KEY (creator_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE doi_request ADD CONSTRAINT FK_715B8DDFD079F553 FOREIGN KEY (modifier_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE person_data_repository ADD CONSTRAINT FK_524FAD8F217BBB47 FOREIGN KEY (person_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE person_data_repository ADD CONSTRAINT FK_524FAD8FA18BC0DD FOREIGN KEY (data_repository_id) REFERENCES data_repository (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE person_data_repository ADD CONSTRAINT FK_524FAD8FD60322AC FOREIGN KEY (role_id) REFERENCES data_repository_role (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE person_data_repository ADD CONSTRAINT FK_524FAD8F61220EA6 FOREIGN KEY (creator_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE person_data_repository ADD CONSTRAINT FK_524FAD8FD079F553 FOREIGN KEY (modifier_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE publication ADD CONSTRAINT FK_AF3C677961220EA6 FOREIGN KEY (creator_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE publication ADD CONSTRAINT FK_AF3C6779D079F553 FOREIGN KEY (modifier_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE person ADD CONSTRAINT FK_34DCD17661220EA6 FOREIGN KEY (creator_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE person ADD CONSTRAINT FK_34DCD176D079F553 FOREIGN KEY (modifier_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE account ADD CONSTRAINT FK_7D3656A4217BBB47 FOREIGN KEY (person_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE account ADD CONSTRAINT FK_7D3656A43E4A79C1 FOREIGN KEY (password_id) REFERENCES password (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE account ADD CONSTRAINT FK_7D3656A461220EA6 FOREIGN KEY (creator_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE account ADD CONSTRAINT FK_7D3656A4D079F553 FOREIGN KEY (modifier_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE password ADD CONSTRAINT FK_35C246D59B6B5FBA FOREIGN KEY (account_id) REFERENCES account (person_id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE password ADD CONSTRAINT FK_35C246D561220EA6 FOREIGN KEY (creator_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE password ADD CONSTRAINT FK_35C246D5D079F553 FOREIGN KEY (modifier_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE dif ADD CONSTRAINT FK_A071AE6D324E97C7 FOREIGN KEY (primary_point_of_contact_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE dif ADD CONSTRAINT FK_A071AE6DBE394C04 FOREIGN KEY (secondary_point_of_contact_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE dif ADD CONSTRAINT FK_A071AE6D61220EA6 FOREIGN KEY (creator_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE dif ADD CONSTRAINT FK_A071AE6DD079F553 FOREIGN KEY (modifier_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE funding_organization ADD CONSTRAINT FK_2A1BCCA0A18BC0DD FOREIGN KEY (data_repository_id) REFERENCES data_repository (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE funding_organization ADD CONSTRAINT FK_2A1BCCA061220EA6 FOREIGN KEY (creator_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE funding_organization ADD CONSTRAINT FK_2A1BCCA0D079F553 FOREIGN KEY (modifier_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE data_repository_role ADD CONSTRAINT FK_91F6449561220EA6 FOREIGN KEY (creator_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE data_repository_role ADD CONSTRAINT FK_91F64495D079F553 FOREIGN KEY (modifier_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE funding_organization_role ADD CONSTRAINT FK_39E8B4E061220EA6 FOREIGN KEY (creator_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE funding_organization_role ADD CONSTRAINT FK_39E8B4E0D079F553 FOREIGN KEY (modifier_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE data_repository ADD CONSTRAINT FK_93CB6D1461220EA6 FOREIGN KEY (creator_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE data_repository ADD CONSTRAINT FK_93CB6D14D079F553 FOREIGN KEY (modifier_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE research_group ADD CONSTRAINT FK_EB46262173FB1572 FOREIGN KEY (funding_cycle_id) REFERENCES funding_cycle (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE research_group ADD CONSTRAINT FK_EB46262161220EA6 FOREIGN KEY (creator_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE research_group ADD CONSTRAINT FK_EB462621D079F553 FOREIGN KEY (modifier_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE metadata ADD CONSTRAINT FK_4F143414D47C2D1B FOREIGN KEY (dataset_id) REFERENCES dataset (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE metadata ADD CONSTRAINT FK_4F14341461220EA6 FOREIGN KEY (creator_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE metadata ADD CONSTRAINT FK_4F143414D079F553 FOREIGN KEY (modifier_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE research_group_role ADD CONSTRAINT FK_BA29D77261220EA6 FOREIGN KEY (creator_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE research_group_role ADD CONSTRAINT FK_BA29D772D079F553 FOREIGN KEY (modifier_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE person_funding_organization ADD CONSTRAINT FK_CE5D61F4217BBB47 FOREIGN KEY (person_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE person_funding_organization ADD CONSTRAINT FK_CE5D61F45213C9D4 FOREIGN KEY (funding_organization_id) REFERENCES funding_organization (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE person_funding_organization ADD CONSTRAINT FK_CE5D61F4D60322AC FOREIGN KEY (role_id) REFERENCES funding_organization_role (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE person_funding_organization ADD CONSTRAINT FK_CE5D61F461220EA6 FOREIGN KEY (creator_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE person_funding_organization ADD CONSTRAINT FK_CE5D61F4D079F553 FOREIGN KEY (modifier_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE person_token ADD CONSTRAINT FK_F301BEFF217BBB47 FOREIGN KEY (person_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE person_token ADD CONSTRAINT FK_F301BEFF61220EA6 FOREIGN KEY (creator_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE person_token ADD CONSTRAINT FK_F301BEFFD079F553 FOREIGN KEY (modifier_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE person_research_group ADD CONSTRAINT FK_E9B161F217BBB47 FOREIGN KEY (person_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE person_research_group ADD CONSTRAINT FK_E9B161F3AF8E8D FOREIGN KEY (research_group_id) REFERENCES research_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE person_research_group ADD CONSTRAINT FK_E9B161FD60322AC FOREIGN KEY (role_id) REFERENCES research_group_role (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE person_research_group ADD CONSTRAINT FK_E9B161F61220EA6 FOREIGN KEY (creator_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE person_research_group ADD CONSTRAINT FK_E9B161FD079F553 FOREIGN KEY (modifier_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE dataset_publication ADD CONSTRAINT FK_3FA681C138B217A7 FOREIGN KEY (publication_id) REFERENCES publication (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE dataset_publication ADD CONSTRAINT FK_3FA681C1D47C2D1B FOREIGN KEY (dataset_id) REFERENCES dataset (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE dataset_publication ADD CONSTRAINT FK_3FA681C161220EA6 FOREIGN KEY (creator_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE dataset_publication ADD CONSTRAINT FK_3FA681C1D079F553 FOREIGN KEY (modifier_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE publication_citation ADD CONSTRAINT FK_D5DA692F38B217A7 FOREIGN KEY (publication_id) REFERENCES publication (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE publication_citation ADD CONSTRAINT FK_D5DA692F61220EA6 FOREIGN KEY (creator_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE publication_citation ADD CONSTRAINT FK_D5DA692FD079F553 FOREIGN KEY (modifier_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE funding_cycle ADD CONSTRAINT FK_37E9C7605213C9D4 FOREIGN KEY (funding_organization_id) REFERENCES funding_organization (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE funding_cycle ADD CONSTRAINT FK_37E9C76061220EA6 FOREIGN KEY (creator_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE funding_cycle ADD CONSTRAINT FK_37E9C760D079F553 FOREIGN KEY (modifier_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    /**
     * Drop all objects created by this baseline version.
     *
     * @param Schema $schema The DBAL schema.
     *
     * @return void
     */
    public function down(Schema $schema)
    {
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'postgresql', 'Migration can only be executed safely on \'postgresql\'.');

        $this->addSql('ALTER TABLE dataset_submission DROP CONSTRAINT FK_FEFE73FCD47C2D1B');
        $this->addSql('ALTER TABLE metadata DROP CONSTRAINT FK_4F143414D47C2D1B');
        $this->addSql('ALTER TABLE dataset_publication DROP CONSTRAINT FK_3FA681C1D47C2D1B');
        $this->addSql('ALTER TABLE dataset DROP CONSTRAINT FK_B7A041D08488BA54');
        $this->addSql('ALTER TABLE dataset_publication DROP CONSTRAINT FK_3FA681C138B217A7');
        $this->addSql('ALTER TABLE publication_citation DROP CONSTRAINT FK_D5DA692F38B217A7');
        $this->addSql('ALTER TABLE dataset DROP CONSTRAINT FK_B7A041D061220EA6');
        $this->addSql('ALTER TABLE dataset DROP CONSTRAINT FK_B7A041D0D079F553');
        $this->addSql('ALTER TABLE dataset_submission DROP CONSTRAINT FK_FEFE73FC61220EA6');
        $this->addSql('ALTER TABLE dataset_submission DROP CONSTRAINT FK_FEFE73FCD079F553');
        $this->addSql('ALTER TABLE doi_request DROP CONSTRAINT FK_715B8DDF61220EA6');
        $this->addSql('ALTER TABLE doi_request DROP CONSTRAINT FK_715B8DDFD079F553');
        $this->addSql('ALTER TABLE person_data_repository DROP CONSTRAINT FK_524FAD8F217BBB47');
        $this->addSql('ALTER TABLE person_data_repository DROP CONSTRAINT FK_524FAD8F61220EA6');
        $this->addSql('ALTER TABLE person_data_repository DROP CONSTRAINT FK_524FAD8FD079F553');
        $this->addSql('ALTER TABLE publication DROP CONSTRAINT FK_AF3C677961220EA6');
        $this->addSql('ALTER TABLE publication DROP CONSTRAINT FK_AF3C6779D079F553');
        $this->addSql('ALTER TABLE person DROP CONSTRAINT FK_34DCD17661220EA6');
        $this->addSql('ALTER TABLE person DROP CONSTRAINT FK_34DCD176D079F553');
        $this->addSql('ALTER TABLE account DROP CONSTRAINT FK_7D3656A4217BBB47');
        $this->addSql('ALTER TABLE account DROP CONSTRAINT FK_7D3656A461220EA6');
        $this->addSql('ALTER TABLE account DROP CONSTRAINT FK_7D3656A4D079F553');
        $this->addSql('ALTER TABLE password DROP CONSTRAINT FK_35C246D561220EA6');
        $this->addSql('ALTER TABLE password DROP CONSTRAINT FK_35C246D5D079F553');
        $this->addSql('ALTER TABLE dif DROP CONSTRAINT FK_A071AE6D324E97C7');
        $this->addSql('ALTER TABLE dif DROP CONSTRAINT FK_A071AE6DBE394C04');
        $this->addSql('ALTER TABLE dif DROP CONSTRAINT FK_A071AE6D61220EA6');
        $this->addSql('ALTER TABLE dif DROP CONSTRAINT FK_A071AE6DD079F553');
        $this->addSql('ALTER TABLE funding_organization DROP CONSTRAINT FK_2A1BCCA061220EA6');
        $this->addSql('ALTER TABLE funding_organization DROP CONSTRAINT FK_2A1BCCA0D079F553');
        $this->addSql('ALTER TABLE data_repository_role DROP CONSTRAINT FK_91F6449561220EA6');
        $this->addSql('ALTER TABLE data_repository_role DROP CONSTRAINT FK_91F64495D079F553');
        $this->addSql('ALTER TABLE funding_organization_role DROP CONSTRAINT FK_39E8B4E061220EA6');
        $this->addSql('ALTER TABLE funding_organization_role DROP CONSTRAINT FK_39E8B4E0D079F553');
        $this->addSql('ALTER TABLE data_repository DROP CONSTRAINT FK_93CB6D1461220EA6');
        $this->addSql('ALTER TABLE data_repository DROP CONSTRAINT FK_93CB6D14D079F553');
        $this->addSql('ALTER TABLE research_group DROP CONSTRAINT FK_EB46262161220EA6');
        $this->addSql('ALTER TABLE research_group DROP CONSTRAINT FK_EB462621D079F553');
        $this->addSql('ALTER TABLE metadata DROP CONSTRAINT FK_4F14341461220EA6');
        $this->addSql('ALTER TABLE metadata DROP CONSTRAINT FK_4F143414D079F553');
        $this->addSql('ALTER TABLE research_group_role DROP CONSTRAINT FK_BA29D77261220EA6');
        $this->addSql('ALTER TABLE research_group_role DROP CONSTRAINT FK_BA29D772D079F553');
        $this->addSql('ALTER TABLE person_funding_organization DROP CONSTRAINT FK_CE5D61F4217BBB47');
        $this->addSql('ALTER TABLE person_funding_organization DROP CONSTRAINT FK_CE5D61F461220EA6');
        $this->addSql('ALTER TABLE person_funding_organization DROP CONSTRAINT FK_CE5D61F4D079F553');
        $this->addSql('ALTER TABLE person_token DROP CONSTRAINT FK_F301BEFF217BBB47');
        $this->addSql('ALTER TABLE person_token DROP CONSTRAINT FK_F301BEFF61220EA6');
        $this->addSql('ALTER TABLE person_token DROP CONSTRAINT FK_F301BEFFD079F553');
        $this->addSql('ALTER TABLE person_research_group DROP CONSTRAINT FK_E9B161F217BBB47');
        $this->addSql('ALTER TABLE person_research_group DROP CONSTRAINT FK_E9B161F61220EA6');
        $this->addSql('ALTER TABLE person_research_group DROP CONSTRAINT FK_E9B161FD079F553');
        $this->addSql('ALTER TABLE dataset_publication DROP CONSTRAINT FK_3FA681C161220EA6');
        $this->addSql('ALTER TABLE dataset_publication DROP CONSTRAINT FK_3FA681C1D079F553');
        $this->addSql('ALTER TABLE publication_citation DROP CONSTRAINT FK_D5DA692F61220EA6');
        $this->addSql('ALTER TABLE publication_citation DROP CONSTRAINT FK_D5DA692FD079F553');
        $this->addSql('ALTER TABLE funding_cycle DROP CONSTRAINT FK_37E9C76061220EA6');
        $this->addSql('ALTER TABLE funding_cycle DROP CONSTRAINT FK_37E9C760D079F553');
        $this->addSql('ALTER TABLE password DROP CONSTRAINT FK_35C246D59B6B5FBA');
        $this->addSql('ALTER TABLE account DROP CONSTRAINT FK_7D3656A43E4A79C1');
        $this->addSql('ALTER TABLE dataset DROP CONSTRAINT FK_B7A041D031C84D2E');
        $this->addSql('ALTER TABLE person_funding_organization DROP CONSTRAINT FK_CE5D61F45213C9D4');
        $this->addSql('ALTER TABLE funding_cycle DROP CONSTRAINT FK_37E9C7605213C9D4');
        $this->addSql('ALTER TABLE person_data_repository DROP CONSTRAINT FK_524FAD8FD60322AC');
        $this->addSql('ALTER TABLE person_funding_organization DROP CONSTRAINT FK_CE5D61F4D60322AC');
        $this->addSql('ALTER TABLE person_data_repository DROP CONSTRAINT FK_524FAD8FA18BC0DD');
        $this->addSql('ALTER TABLE funding_organization DROP CONSTRAINT FK_2A1BCCA0A18BC0DD');
        $this->addSql('ALTER TABLE dataset DROP CONSTRAINT FK_B7A041D03AF8E8D');
        $this->addSql('ALTER TABLE person_research_group DROP CONSTRAINT FK_E9B161F3AF8E8D');
        $this->addSql('ALTER TABLE person_research_group DROP CONSTRAINT FK_E9B161FD60322AC');
        $this->addSql('ALTER TABLE research_group DROP CONSTRAINT FK_EB46262173FB1572');
        $this->addSql('DROP SEQUENCE dataset_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE dataset_submission_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE doi_request_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE person_data_repository_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE publication_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE person_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE password_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE dif_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE funding_organization_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE data_repository_role_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE funding_organization_role_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE data_repository_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE research_group_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE metadata_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE research_group_role_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE person_funding_organization_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE person_research_group_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE dataset_publication_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE publication_citation_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE funding_cycle_id_seq CASCADE');
        $this->addSql('DROP TABLE dataset');
        $this->addSql('DROP TABLE dataset_audit');
        $this->addSql('DROP TABLE dataset_submission');
        $this->addSql('DROP TABLE dataset_submission_audit');
        $this->addSql('DROP TABLE doi_request');
        $this->addSql('DROP TABLE person_data_repository');
        $this->addSql('DROP TABLE person_data_repository_audit');
        $this->addSql('DROP TABLE publication');
        $this->addSql('DROP TABLE person');
        $this->addSql('DROP TABLE person_audit');
        $this->addSql('DROP TABLE account');
        $this->addSql('DROP TABLE password');
        $this->addSql('DROP TABLE dif');
        $this->addSql('DROP TABLE dif_audit');
        $this->addSql('DROP TABLE funding_organization');
        $this->addSql('DROP TABLE funding_organization_audit');
        $this->addSql('DROP TABLE data_repository_role');
        $this->addSql('DROP TABLE funding_organization_role');
        $this->addSql('DROP TABLE data_repository');
        $this->addSql('DROP TABLE data_repository_audit');
        $this->addSql('DROP TABLE research_group');
        $this->addSql('DROP TABLE research_group_audit');
        $this->addSql('DROP TABLE metadata');
        $this->addSql('DROP TABLE research_group_role');
        $this->addSql('DROP TABLE person_funding_organization');
        $this->addSql('DROP TABLE person_funding_organization_audit');
        $this->addSql('DROP TABLE person_token');
        $this->addSql('DROP TABLE person_research_group');
        $this->addSql('DROP TABLE person_research_group_audit');
        $this->addSql('DROP TABLE dataset_publication');
        $this->addSql('DROP TABLE publication_citation');
        $this->addSql('DROP TABLE funding_cycle');
        $this->addSql('DROP TABLE funding_cycle_audit');
        $this->addSql('DROP TABLE revisions');
    }
}
