#!/usr/bin/perl -w

use strict;
use Proc::Daemon;
use Getopt::Long;

my $pidfile = '/var/run/filerd.pid';
GetOptions("pidfile=s" => \$pidfile);

my $daemon = Proc::Daemon->new( pid_file => $pidfile );

$daemon->Init;
chmod 0644, $pidfile;

my $continue = 1;
$SIG{'TERM'} = sub { $continue = 0 };
$SIG{'HUP'} = \&trigger_filer;

while ($continue) {
    sleep(10);
}

sub trigger_filer {
    my $child_pid = $daemon->Init;
    unless($child_pid) {
        exec('/usr/local/griidc/filer/filer');
    }
}
